### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/php-sniffs#50]
Is there any CF specific things here? @Solomonic AFAIK, it's just rules, making this public would mean, it could go to packagist as well, making installation of boilerplate very easy (as it's public)

As of now boilerplate is public, but this isn't, so someone might get confused what crazyfactory/sniffs is. And again, this doesn't contain anything private, so what do you think?

**Comment by Solomonic** [comment]
I agree, its public now
